alaviss/tree-sitter-nim

- grammar.js
- src/grammar.json
This prevents multiple syntax node being created for each characters but
instead try to group them whenever possible.
> tokenize interpreted string text

- corpus/declarations.txt
- corpus/expressions.txt
- corpus/extras.txt
- grammar.js
- src/grammar.json
- src/node-types.json
- src/scanner.cc
Previously, lexer's layouting tokens are composed of both newlines and
whitespaces. This required disambiguation at the lexer level and things
like DEDENT -> INDENT_EQ required lexing tricks such as expecting the
other token to be requested precisely after DEDENT.
Stuff like lines into comment also required special tokens like
SPACES_BEFORE_COMMENT.
This commit decouples newlines from layouting tokens and uses the
grammar to specify them. This brings several advantages:
* Comments can be transparently handled since extra tokens are scanned
automatically between newline -> layout.
* The parser can catch ambiguous definition at compile time and require
explicit disambiguation.
* The loosened tokens can be used as extra tokens in the grammar to
track indentation across all lines. This …
> simplify lexer and offload more into grammar

- corpus/declarations.txt
- corpus/expressions.txt
- corpus/statements.txt
- grammar.js
- src/grammar.json
- src/node-types.json
- src/scanner.cc
This allows us to remove 11 external scanning nodes. Tie breaking against command call & prefix is now done solely on the prefix operator.
Symbolic operators are now exposed as nodes to allow syntax queries to match against them.
Due to size explosion, unicode operators are disabled.
Included are some fixes for scanner flags reset on new line.
> put infix operators as inline within the grammar

- .clangd
- corpus/deviations.txt
- corpus/expressions.txt
- corpus/extras.txt
- corpus/literals.txt
- grammar.js
- src/grammar.json
- src/node-types.json
- src/scanner.cc
A lot of tokens were externalized to deal with conflicts between them and other external tokens.
This presented an issue: tree-sitter could not merge parse states automatically since it has to be mindful of these external tokens.
This PR attempts to pull back on the number of externals used to the bare minimum and accept inaccuracies where applicable (ie. no one would write code like this).
Most of the magic is done by making extras purely internal lexer first. This gives the external lexer complete confidence of where the extras are invoked without fighting with the internal lexer.
Doing this also allowed us to expand `escape_sequence` to more nodes, facilitating better syntax highlighting.
The next big thing is the unconditional treatment of `elif`/`else`/`except`/`finally` as line …
> reduce the number of externals in the grammar and expand strings nodes

- corpus/declarations.txt
- grammar.js
- src/grammar.json
- src/node-types.json
Fix erroneous use of `_object_field_declaration_list` in
`conditional_declaration`. It should've been the branch
variant to allow for inline declaration.
> fix inline conditional declaration

- corpus/expressions.txt
- grammar.js
- src/grammar.json
- src/scanner.cc
Now that the parser size has gone down, support for inline block termination of `]`, `}` and `.}` can now be enabled.
> enable inline block termination for other structures

- .github/workflows/ci.yml
- corpus/declarations.txt
- corpus/expressions.txt
- corpus/extras.txt
- corpus/statements.txt
- grammar.js
- src/grammar.json
- src/node-types.json
- src/scanner.cc
This PR brings support for more complex Nim structure, enabled by the parser size reduction effort done by earlier PRs.
However, as a result of this, generating the parser is now costlier at 7GiB of memory. The resulting parser is /slightly/ smaller at 118MiB.
New structures supported:
- Command call with full-fledged expression as arguments
- Full expression support in enum value declarations
- `(var T, var U)` within typedesc
- `cast(raises: [])`
Fixed bugs:
- `layout_empty` not emitted for lower indentation levels
- Block comments may mess up initial indentation determination
> supports more structures and many bug fixes

- grammar.js
- src/grammar.json
- src/node-types.json
Apparently this helps with writing injection queries.
Ref: https://github.com/alaviss/tree-sitter-nim/pull/32#issuecomment-1717850053
> change long string opening from regex to literal choice

- corpus/declarations.txt
- corpus/expressions.txt
- grammar.js
- src/grammar.json
- src/scanner.cc
This is required to correctly handle `var x *: typ`.
This does require some external parser changes to avoid `*` being consumed as unary when exported symbol is a valid interpretation.
Fixes https://github.com/alaviss/tree-sitter-nim/issues/35
> split * and : into two tokens

- corpus/declarations.txt
- grammar.js
- src/grammar.json
This seems to be a grammar quirk of Nim.
Verified against Nim 2.0.0.
Fixes https://github.com/alaviss/tree-sitter-nim/issues/38
> allow symbol_declaration_list to harbor a trailing comma

- corpus/declarations.txt
- corpus/errors.txt
- grammar.js
- src/grammar.json
- src/scanner.cc
A couple improvements to error recovery:
- `case` and `when` within an object can now tolerate incomplete code. This change was done to match what is done for them outside of an object declaration.
- `scanner.cc` will no longer emit `layout_empty` during error recovery, which should prevent some extreme interpretation due to `layout_empty` being valid in only a handful of places.
Example:
```nim
type
X = object
case y
of x
```
Before:
```
(source_file [0, 0] - [4, 0]
(ERROR [0, 0] - [4, 0]
(type_symbol_declaration [1, 2] - [1, 3]
name: (identifier [1, 2] - [1, 3]))
(variant_discriminator_declaration [2, 9] - [2, 10]
(symbol_declaration_list [2, 9] - [2, 10]
(symbol_declaration [2, 9] - [2, 10]
name: (identifier [2, 9] - [2, 10]))))
(identifier [3, 7] - [3, 8])))
```
After:
``` …
```
> grammar, scanner: better error recovery

- .github/workflows/ci.yml
tree-sitter has been generating different parser depending on the OS, making the CI check useless.
Ref https://github.com/alaviss/tree-sitter-nim/issues/33
> ci: demote parser mismatch into warnings

- .prettierrc
- corpus/errors.txt
- grammar.js
- src/grammar.json
- src/scanner.c
* Layouts are ended when it is detected that such event happens
regardless of whether it is correct to do so. This allows for
stronger error recovery as the parser can reliably detect where
a layout ends.
* Layouts now terminates at the end of each statements or blocks, rather
than collecting up to the next statement.
* Layout termination now plays a lot nicer in recovery scenarios by
issuing a forced change to the scanner state. This makes the parser
respects layout termination during recovery, resulting in much better
syntax tree on errors.
* The body of an indented statement list is now optional. While this
construct cannot be generated by normal means as the scanner must see
content to even start a block, they can happen due to errors within
the block. Allowing the block to be empty …
> major behavior changes to layouting

- corpus/declarations.txt
- corpus/deviations.txt
- corpus/expressions.txt
- corpus/extras.txt
- corpus/literals.txt
- corpus/statements.txt
- grammar.js
- queries/highlights.scm
- src/grammar.json
- src/node-types.json
- src/scanner.c
- test/highlight/expressions.nim
Contents of string and comment types are now spun out of the main node. This should make it easier to query against by avoiding offset dances.
As an aside, the string literal type is also specialized into different variants, as a consistency change to align with what was done for comment types.
> improve capture queries by specializing types

- corpus/expressions.txt
- grammar.js
- src/grammar.json
- src/scanner.c
In Nim these contexts are allowed to have indentation below that of the current layout.
Fixes 9cda851ed098e3f0a501e2c676ca26dc6a1a8884
> make (), [], {} and {.} inhibit layout end

- corpus/errors.txt
It was discovered that prior to 9cda851ed098e3f0a501e2c676ca26dc6a1a8884 the parser accepted this code.
> add a test for hanging dot expression

- corpus/errors.txt
- corpus/expressions.txt
- grammar.js
- src/grammar.json
- src/scanner.c
Within an if/try context, any keyword like else or except can be used to terminate any inner blocks.
This commit also allows the parser to properly terminate statements when a continuing keyword shows up at the wrong places.
Fixes https://github.com/alaviss/tree-sitter-nim/issues/41
> implement termination rule for if/try

- corpus/declarations.txt
- corpus/expressions.txt
- grammar.js
- src/grammar.json
- src/node-types.json
This pull includes two changes:
- Make sure `field` pin-point to the interested node
- Improve field consistency within the grammar and introduce more fields for other complex structures.
This pull contains breaking change for a few field names.
> improve field accuracy and introduce new fields

- corpus/errors.txt
- src/scanner.c
Allowing layout_end on EOF allows the parser to close and isolate grammar portions where layout_end is typically not allowed (ie. in parentheses), which enabled better error recovery.
The empty termination hack does not seem to contribute anymore with this change and was removed.
With this change, we also remove the use of synchronize node for fixing after newline. Instead it is cleared based on column position at the start of the lexer. This should reduce errors from node reuse, but is more or less a hunch since it is hard to test incremental parsing.
Fixes https://github.com/alaviss/tree-sitter-nim/issues/64.
> scanner: allow end on EOF and use column for flag invalidation

- corpus/declarations.txt
- grammar.js
- src/grammar.json
This syntax quirk is utilized by `system.nim`
Fixes https://github.com/alaviss/tree-sitter-nim/issues/66.
> make type declaration RHS optional

- src/scanner.c
In certain scenarios, the parser might crash due to an OOB in tree-sitter during get_column() at EOF. Since tree-sitter still hasn't released a new version with the fix, we will have to solve it here ourselves.
Ref https://github.com/tree-sitter/tree-sitter/issues/2563
> scanner: add workaround for column at EOF

- corpus/declarations.txt
- grammar.js
- src/grammar.json
- src/node-types.json
This should align these with their when/case conditional counterparts.
> add missing consequence field to object declaration

- src/scanner.c
This allows the allocator to be swapped out by the library user.
> scanner: switch to tree-sitter allocator

- Cargo.lock
- Cargo.toml
- Makefile
- package-lock.json
- package.json
- pyproject.toml
As an aside, some Cargo dependencies are updated due to how lockfile updates work with Cargo.
> bump version to 0.6.0

- grammar.js
- src/grammar.json
- src/scanner.c
Since unary operator processing in external scanner conflicts with export marker, the export marker was made into a non-terminal rule that was also an external symbol, where the sole reason for the external symbol was to allow the unary operator handler in the external parser know that the marker `*` is meant to be a marker and not an unary operator.
Recent tree-sitter changes has forbade this particular usage. As such, switch to using a signal token (an optional token that is an external) to let the external scanner know the context it is handling.
Ref: https://github.com/alaviss/tree-sitter-nim/issues/90#issuecomment-2211742258
Ref: https://github.com/tree-sitter/tree-sitter/pull/2577
> use explicit hint tokens for export marker

- .github/workflows/ci.yml
- .gitignore
- src/scanner.c
WASM builds does not expose symbols for printing. As such, settle for simply crashing.
Also add WASM build step to CI to verify that it can be built.
This commit allows the grammar to be used with the Zed editor.
> scanner: disable printing for WASM
